### ISSUE TITLE
your sample code cause a compile error

### ISSUE THREAD

**Issue by genru** [Emeryao/WechatJSSDK.d.ts#6]
I follow your sample code in README, without imprt any file and do same thing as you sampled, when I 
`ng build`, an error displayed
```
ERROR in src/app/rank/rank.component.ts(42,9): error TS2304: Cannot find name 'wx'.
```
```
        wx.config(res);
        wx.ready(() => {
          wx.onMenuShareAppMessage({
            link: this.document.location.href,
            title: kTitle[this.type],
            desc: '主播，标签，机构，类目，流量，首页入围等排名',
            imgUrl: 'http://weixin.udaren.com/assets/images/logo.png'
          });
        })
```

it seems wx does not declared, could you update your document to show how to make it work?

**Comment by emeryao** [comment]
ok I'll check it up

**Comment by emeryao** [comment]
Have you include `jweixin.d.ts` to your project folder ?

**Comment by genru** [comment]
'include'? I guess no, I do not understand how to do it? I just `yarn install` and use it in ts file.

**Comment by emeryao** [comment]
this repo does not support `yarn` for now
please follow the [`install`](https://github.com/Emeryao/typed-jweixin#install) documentation

**Comment by genru** [comment]
thank you for your instruction. unfortunately it does not work, error remains.
I believe `yarn` is compatible with `npm`, it maybe is not the cause.

belowing are what I followed
1) install jweixin
```
npm install typed-jweixin --save-dev
```
2) try to build prject
```
ng build
```

I use angular 6, is this a angular 6 compatibility issue?

**Comment by emeryao** [comment]
I'm sorry but `yarn` is not compatible with `npm` in this case
cause the version in [`package.json`](https://github.com/Emeryao/typed-jweixin/blob/master/package.json#L29) is **`1.0.0-update.1`** which `yarn` does not support while `npm` does

**Comment by emeryao** [comment]
and there should not be any compatibility issues with `@angular@6`

**Comment by emeryao** [comment]
so just make sure you've include the `jweixin.d.ts` in your project
if so please let me know and I'll do some further investigation

**Comment by emeryao** [comment]
could you pop up some `error message` that may helps ?

**Comment by genru** [comment]
error message shows
```
ERROR in src/app/rank/rank.component.ts(42,9): error TS2304: Cannot find name 'wx'.
```
`index.d.ts` already exists in `node_modules/@types/jweixin`.

does not find `jweixin.d.ts` in project folder. hope this helpful.

**Comment by emeryao** [comment]
> `index.d.ts` already exists in `node_modules/@types/jweixin`.
> does not find `jweixin.d.ts` in project folder. hope this helpful.

this is expected that how the declaration file is being included if the `node_modules/@types/jweixin/index.d.ts` have the same content with `jweixin.d.ts`

I'll do some investigation.

PS it's appreciated if you pop up some pieces of your code that errors

**Comment by genru** [comment]
I have an component to show rank data. and I need to config wechat jssdk first.

```
import { Component, OnInit, Inject } from '@angular/core';
import { ActivatedRoute, Params } from '@angular/router';
import { HttpClient, HttpParams } from '@angular/common/http';
import { environment } from '../../environments/environment';
import { Title, DOCUMENT } from '@angular/platform-browser';

@Component({
  selector: 'app-rank',
  templateUrl: './rank.component.html',
  styleUrls: ['./rank.component.css']
})
export class RankComponent implements OnInit {

  type: number;
  cate: number;
  shopTopPillows = false;
  dataSource = [];
  showQR = false;
  constructor(private route: ActivatedRoute, private http: HttpClient, private titleService: Title
    , @Inject(DOCUMENT) private document: any) { }

  ngOnInit() {
    this.http.get('/wechat/config').subscribe((data: any) => {
      wx.config(data);      // <--- fail here
    });
  }

}
```
this is what i do.

**Comment by emeryao** [comment]
hi @genru I got the tricky  🎉 

projects created with `ng new` have a `./src/tsconfig.app.json` with default content 
```json
{
    "extends": "../tsconfig.json",
    "compilerOptions": {
        "outDir": "../out-tsc/app",
        "types": []
    },
    "exclude": []
}
```

just **remove** the line `"types":[]` solves this issue 🤣

**Comment by genru** [comment]
thanks for your workaround for this, if some update made to resolve this issue would be great, or consider to update README.

thanks

**Comment by emeryao** [comment]
[REAEME.me](https://github.com/Emeryao/typed-jweixin/blob/master/README.md) already updated 😆

**Comment by emeryao** [comment]
@genru 
as you can see [here](https://github.com/aws/aws-sdk-js#with-angular) aws said the same 😝
